//  Copyright (c) 2015 fournova GmbH. All rights reserved.
// -----------------------------------------------------------------------------
// THIS FILE IS AUTO GENERATED BY FOURNOVA ERROR GENERATOR - DO NOT EDIT!
// -----------------------------------------------------------------------------

#import <Foundation/Foundation.h>

/** @name Error Domain */

extern NSString *const FNGitErrorDomain;

/** @name Error UserInfo Keys */

extern NSString *const FNGitBinaryVersionErrorKey;
extern NSString *const FNGitCommandCallErrorKey;
extern NSString *const FNGitErrorOutputErrorKey;
extern NSString *const FNGitCommandExitCodeErrorKey;
extern NSString *const FNGitCommandErrorOutputErrorKey;
extern NSString *const FNGitCommandStandardOutputErrorKey;
extern NSString *const FNGitCommandEnvironmentErrorKey;
extern NSString *const FNGitConfigFileErrorKey;
extern NSString *const FNGitConfigKeyErrorKey;
extern NSString *const FNGitConfigValueErrorKey;
extern NSString *const FNGitConfigNewSectionNameErrorKey;
extern NSString *const FNGitConfigSectionNameErrorKey;
extern NSString *const FNGitDestinationFilePathErrorKey;
extern NSString *const FNGitFilePathErrorKey;
extern NSString *const FNGitFilePathsErrorKey;
extern NSString *const FNGitIgnoresPathErrorKey;
extern NSString *const FNGitNewRefNameErrorKey;
extern NSString *const FNGitNewRemoteNameErrorKey;
extern NSString *const FNGitNewSubmoduleNameErrorKey;
extern NSString *const FNGitObjectHashErrorKey;
extern NSString *const FNGitObjectReferenceErrorKey;
extern NSString *const FNGitOutputParserNameErrorKey;
extern NSString *const FNGitOutputParserLineErrorKey;
extern NSString *const FNGitPatchErrorKey;
extern NSString *const FNGitPatchLineNumberErrorKey;
extern NSString *const FNGitRebaseCurrentStepErrorKey;
extern NSString *const FNGitRebaseLastStepErrorKey;
extern NSString *const FNGitRebaseSubjectErrorKey;
extern NSString *const FNGitRefNameErrorKey;
extern NSString *const FNGitRefSpecErrorKey;
extern NSString *const FNGitRemoteNameErrorKey;
extern NSString *const FNGitRemoteURLErrorKey;
extern NSString *const FNGitRepositoryPathErrorKey;
extern NSString *const FNGitRevisionErrorKey;
extern NSString *const FNGitSourceFilePathErrorKey;
extern NSString *const FNGitSubmoduleNameErrorKey;
extern NSString *const FNGitSubmodulePathErrorKey;

/** @name Error Codes */

typedef NS_ENUM(NSInteger, FNGitError) {
    FNGitGenericError = 1,
    FNGitAskpassError,
    FNGitOutputParserError,
    FNGitInitRepositoryFileExistsError,
    FNGitInitRepositoryPathNotWritableError,
    FNGitInitRepositoryInvalidPathError,
    FNGitDescriptionReadError,
    FNGitDescriptionWriteError,
    FNGitIgnoresReadError,
    FNGitIgnoresWriteError,
    FNGitAddSubmodulePathOutsideRepositoryError,
    FNGitAddSubmodulePathAlreadyExistsError,
    FNGitAddSubmoduleGitDirectoryAlreadyExistsError,
    FNGitBlobReadError,
    FNGitAddFilesError,
    FNGitApplyPatchCorruptError,
    FNGitApplyPatchWithNoChangesError,
    FNGitApplyPatchWithNoTargetError,
    FNGitApplyStashMergeConflictsError,
    FNGitApplyStashNotFoundError,
    FNGitApplyStashNoStashesError,
    FNGitApplyStashUncommittedChangesError,
    FNGitArchiveFilesError,
    FNGitBadDefaultRevisionError,
    FNGitBadRevisionError,
    FNGitBlobNotFoundError,
    FNGitCheckoutUncommittedChangesError,
    FNGitCommandUsageError,
    FNGitConfigBadValueError,
    FNGitConfigInvalidFileError,
    FNGitConfigKeyNotFoundError,
    FNGitConfigMultipleValuesForKeyError,
    FNGitConfigReadError,
    FNGitConfigSectionNotFoundError,
    FNGitConfigWriteError,
    FNGitCreateBranchFromStashInvalidNameError,
    FNGitCreateBranchFromStashNotFoundError,
    FNGitCreateBranchFromStashNoStashesError,
    FNGitCreateBranchFromStashUncommittedChangesError,
    FNGitCreateBranchInvalidNameError,
    FNGitCreateBranchInvalidObjectError,
    FNGitCreateBranchRefAlreadyExistsError,
    FNGitCreateRemoteAlreadyExistsError,
    FNGitCreateRemoteInvalidNameError,
    FNGitCreateTagAlreadyExistsError,
    FNGitCreateTagInvalidObjectError,
    FNGitDeleteBranchNoSuchBranchError,
    FNGitDeleteCurrentBranchError,
    FNGitDeleteTagNotFoundError,
    FNGitDeleteUnmergedBranchError,
    FNGitDropStashNotFoundError,
    FNGitDropStashNoStashesError,
    FNGitSVNInstallationError,
    FNGitIndexLockError,
    FNGitLogNoSuchRevisionError,
    FNGitMergeConflictsError,
    FNGitMergeUncommittedChangesError,
    FNGitMergeUnmergedChangesError,
    FNGitMergetoolMergeFailedError,
    FNGitMoveFileAlreadyExistsError,
    FNGitMoveFileDestinationDirectoryMissingError,
    FNGitMoveFileNotUnderVersionControlError,
    FNGitMoveFileOutsideRepositoryError,
    FNGitMoveFileSelfTargetError,
    FNGitMoveFileSourceDirectoryEmptyError,
    FNGitMoveFileSourceNotFoundError,
    FNGitNoDefaultMergeBranchError,
    FNGitNoGitRepoError,
    FNGitNoRefsError,
    FNGitNoWorkTreeError,
    FNGitRebaseConflictsError,
    FNGitRebaseUncommittedChangesError,
    FNGitRebaseUnmergedChangesError,
    FNGitRefsReadError,
    FNGitRemoteAuthError,
    FNGitRemoteConnectionError,
    FNGitRemotePushNoUpstreamBranchError,
    FNGitRemotePushRejectedError,
    FNGitRemoteSyncError,
    FNGitRenameBranchInvalidObjectError,
    FNGitRenameBranchRefAlreadyExistsError,
    FNGitRenameRemoteAlreadyExistsError,
    FNGitRenameRemoteInvalidNameError,
    FNGitRemoveOperationNotPermittedError,
    FNGitRemoveFileWithLocalModificationsError,
    FNGitRemoveSubmoduleWithLocalModificationsError,
    FNGitSaveStashInitialCommitError,
    FNGitSubmoduleStatusMissingMappingError,
    FNGitSubmoduleStatusMissingGitDirError,
    FNGitTrackBranchInvalidObjectError,
    FNGitTreeNotATreeObjectError,
    FNGitTreeNotFoundError,
    FNGitUpdateIndexNoSuchFileError,
};

@interface FNGitErrors : NSObject

+ (NSDictionary *)errorCodes;

@end
