#!/bin/sh

SCRIPT_NAME=$(basename $0)
SOURCE="$1"
DESTINATION="$2"

if [ -z "$SOURCE" ] || [ -z "$DESTINATION" ]; then
    echo "Usage: $SCRIPT_NAME SRC DEST"
    exit 1
fi

/bin/mkdir -p "$DESTINATION"
/usr/bin/install "$SOURCE" "$DESTINATION"

exit 0
